create table tca01_ciclo (id_ciclo  serial not null, id_estatus int2 not null, nb_ciclo varchar(50) not null unique, fh_inicio date not null, fh_fin date not null, fh_publicacion date not null, primary key (id_ciclo));
create table tca11_ciclo_actividad (id_ciclo int2 not null, id_actividad int4 not null, fh_inicio date not null, fh_fin date not null, primary key (id_ciclo, id_actividad));
create table tsp03_cp (id_cp  serial not null, id_entidad varchar(2) not null, id_municipio varchar(3) not null, tx_cp varchar(5) not null, nb_asentamiento varchar(100) not null, nb_ciudad varchar(100), st_activo bool not null, primary key (id_cp));
create table tau04_acceso (id_usuario int4 not null, nu_intento int2 not null, fh_intento timestamp(0), fh_bloqueo timestamp(0), primary key (id_usuario));
create table tca02_estatus_ciclo (id_estatus  serial not null, nb_estatus varchar(50) not null, ds_estatus varchar(250) not null, st_activo bool not null, primary key (id_estatus));
create table tca05_convocatoria (id_convocatoria int2 not null, fh_inicio date not null, fh_fin date not null, primary key (id_convocatoria));
create table tca04_requisito (id_requisito  serial not null, nb_requisito varchar(100) not null unique, primary key (id_requisito));
create table tca06_criterio (id_criterio  serial not null, nb_criterio varchar(100) not null, st_periodo bool not null, st_costo bool not null, primary key (id_criterio));
create table tca09_convocatoria_criterio (id_convocatoria int2 not null, id_criterio int2 not null, nu_costo float4 not null, nu_ponderacion int2 not null, nu_min int2 not null, nu_max int2 not null, st_adjunto bool not null, primary key (id_convocatoria, id_criterio));
create table tca08_convocatoria_requisito (id_convocatoria int2 not null, id_requisito int2 not null, st_obligatorio bool not null, st_adjunto bool not null, primary key (id_convocatoria, id_requisito));
create table tca07_actividad (id_actividad  serial not null, id_tipo int2 not null, nb_actividad varchar(100), ds_actividad varchar(255), st_activo bool, primary key (id_actividad));
create table tca10_periodo (id_periodo int4 not null, id_convocatoria int2 not null, id_criterio int2 not null, nb_periodo varchar(50) not null, fh_inicio timestamp(0) not null, fh_fin timestamp(0) not null, st_publicacion bool, primary key (id_periodo, id_convocatoria, id_criterio));
create table tad17_entrevistador (id_entrevistador int4 not null, primary key (id_entrevistador));
create table tib08_dia (id_dia  serial not null, nb_dia varchar(10) not null, ds_dia varchar(10) not null, st_dia bool not null, primary key (id_dia));
create table tad16_convocatoria_entrevistador (id_convocatoria int2 not null, id_entrevistador int4 not null, primary key (id_convocatoria, id_entrevistador));
create table tad13_entrevista (id_entrevista  serial not null, id_convocatoria int2 not null, id_aspirante int4 not null, id_entrevistador int4 not null, id_estatus int4 not null, tx_observacion varchar(2000), primary key (id_entrevista));
create table tad11_calificacion_entrevista (id_calificacion  serial not null, nu_calificacion int2 not null, ds_calificacion varchar(100), st_calificacion boolean, primary key (id_calificacion));
create table tad20_contacto (id_contacto  serial not null, id_aspirante int4 not null, id_categoria int2 not null, id_tipo int2 not null, tx_acontacto varchar(250) not null, tx_contacto_a varchar(250), tx_contacto_b varchar(250), tc_emergencia varchar(100), tx_relacion varchar(100), primary key (id_contacto));
create table tad21_cita (id_convocatoria int2 not null, id_aspirante int4 not null, id_entrevistador int4 not null, fh_cita timestamp(0) not null, primary key (id_convocatoria, id_aspirante, id_entrevistador));
create table tad10_rubro_entrevista (id_rubro  serial not null, nb_rubo varchar(50) not null, nu_calificacion int2, st_rubro bool, primary key (id_rubro));
create table tad12_entrevista_rubro (id_entrevista int4 not null, id_rubro int2 not null, id_calificacion int2 not null, primary key (id_entrevista, id_rubro));
create table tad14_recomendacion (id_recomendacion int4 not null, id_recomendador int4, nb_recomendador varchar(100), primary key (id_recomendacion));
create table tad15_estatus_entrevista (id_estatus  serial not null, nb_estatus varchar(50) not null unique, ds_estatus varchar(100) not null, st_activo bool not null, primary key (id_estatus));
create table tad18_direccion (id_direccion  serial not null, id_entidad varchar(2) not null, id_municipio varchar(3) not null, tx_colonia varchar(100), tx_numero_ext varchar(10), tx_numero_int varchar(10), tx_cp varchar(5), tx_calle varchar(100), primary key (id_direccion));
create table tad19_aspirante_direccion (id_direccion int4 not null, id_aspirante int4 not null, id_tipo int2 not null, primary key (id_direccion, id_aspirante, id_tipo));
create table tad07_horario (id_convocatoria int2 not null, id_entrevistador int4 not null, id_dia int2 not null, id_horario int4 not null, tm_inicio time(6), tm_fin time(6), primary key (id_convocatoria, id_entrevistador, id_dia, id_horario));
create table tad04_convocatoria_aspirante (id_convocatoria int2 not null, id_aspirante int4 not null, id_estatus int2 not null, fh_registro int4, primary key (id_convocatoria, id_aspirante));
create table tad09_pago (id_convocatoria int2 not null, id_aspirante int4 not null, id_tipo int2 not null, fh_pago int4, nu_monto float4, primary key (id_convocatoria, id_aspirante));
create table tib09_categoria_pago (id_categoria  serial not null, nb_categoria varchar(50), ds_categoria varchar(100), st_categoria bool, primary key (id_categoria));
create table tib10_tipo_pago (id_tipo  serial not null, id_categoria int2 not null, nb_tipo varchar(50), ds_tipo varchar(100), st_tipo bool, primary key (id_tipo));
create table tau02_usuario (id_usuario int4 not null, tx_login varchar(50) not null unique, tx_password varchar(20) not null, primary key (id_usuario));
create table tad01_estatus_aspirante (id_estatus  serial not null, nb_estatus varchar(50) not null unique, ds_estatus varchar(250) not null, st_activo bool not null, primary key (id_estatus));
create table tad06_informacion_escolar (id_informacion  serial not null, id_aspirante int4 not null, id_nivel int4 not null, tx_nombre varchar(100), st_nacional bool, st_oficial bool, tx_adeudo varchar(500), nu_promedio float4, primary key (id_informacion));
create table tad05_nivel (id_nivel  serial not null, nb_nivel varchar(50), ds_nivel varchar(250), st_activo bool, primary key (id_nivel));
create table tib03_persona (id_persona  serial not null, nb_persona varchar(100) not null, tx_primer_ap varchar(100) not null, tx_segundo_ap varchar(100), tx_curp varchar(18), primary key (id_persona));
create table tad02_aspirante (id_aspirante  serial not null, nb_persona varchar(100), tx_primer_ap varchar(100), tx_segundo_ap varchar(100), tx_curp varchar(18), primary key (id_aspirante));
create table tca03_tipo_actividad (id_tipo  serial not null, nb_tipo varchar(50) not null, ds_tipo varchar(250) not null, st_actividad bool not null, primary key (id_tipo));
create table tib02_direccion (id_direccion  serial not null, id_entidad varchar(2) not null, id_municipio varchar(3) not null, tx_colonia varchar(100) not null, tx_calle varchar(100) not null, tx_numero_ext varchar(10) not null, tx_numero_int varchar(10) not null, tx_cp varchar(5) not null, primary key (id_direccion));
create table tib04_direccion_persona (id_direccion int4 not null, id_persona int4 not null, id_tipo int2 not null, primary key (id_direccion, id_persona, id_tipo));
create table tib01_tipo_direccion (id_tipo  serial not null, nb_tipo varchar(50), ds_tipo varchar(255), st_tipo bool, primary key (id_tipo));
create table tsp01_entidad (id_entidad varchar(2) not null, nb_entidad varchar(35) not null, st_activo bool default 'true' not null, primary key (id_entidad));
create table tsp02_municipio (id_entidad varchar(2) not null, id_municipio varchar(3) not null, nb_municipio varchar(100) not null, st_activo bool default 'true' not null, primary key (id_entidad, id_municipio));
create table alumno (id_persona int4 not null, primary key (id_persona));
create table profesor (id_persona int4 not null, primary key (id_persona));
create table tib06_tipo_contacto (id_tipo  serial not null, nb_tipo varchar(50) not null, ds_tipo varchar(250) not null, st_activo bool not null, primary key (id_tipo));
create table tib07_contacto (id_contacto  serial not null, id_persona int4 not null, id_tipo int2 not null, id_categoria int2 not null, tx_contacto varchar(250) not null, tx_contacto_a varchar(250), tx_contacto_b varchar(250), tx_emergencia varchar(100), tx_relacion varchar(100), primary key (id_contacto));
create table tib05_categoria_contacto (id_categoria  serial not null, nb_categoria varchar(100) not null, ds_categoria varchar(255) not null, st_activo bool not null, primary key (id_categoria));
create table tau01_perfil (id_perfil  serial not null, nb_perfil varchar(50) not null unique, ds_perfil varchar(255) not null, st_perfil bool not null, primary key (id_perfil));
create table tau03_cuenta (id_usuario int4 not null, id_perfil int2 not null, id_cuenta int4 not null, fh_inicio date not null, fh_fin date, primary key (id_usuario, id_perfil, id_cuenta));
create table egresado (id_persona int4 not null, primary key (id_persona));
alter table tau02_usuario add constraint FKtau02_usua255783 foreign key (id_usuario) references tib03_persona;
alter table tib07_contacto add constraint FKtib07_cont706275 foreign key (id_tipo) references tib06_tipo_contacto;
alter table tib07_contacto add constraint FKtib07_cont10814 foreign key (id_persona) references tib03_persona;
alter table tib07_contacto add constraint FKtib07_cont267383 foreign key (id_categoria) references tib05_categoria_contacto;
alter table tau03_cuenta add constraint FKtau03_cuen257797 foreign key (id_perfil) references tau01_perfil;
alter table tau03_cuenta add constraint FKtau03_cuen189100 foreign key (id_usuario) references tau02_usuario;
alter table alumno add constraint FKalumno244362 foreign key (id_persona) references tau02_usuario;
alter table profesor add constraint FKprofesor474636 foreign key (id_persona) references tau02_usuario;
alter table tib04_direccion_persona add constraint FKtib04_dire284703 foreign key (id_direccion) references tib02_direccion;
alter table tib04_direccion_persona add constraint FKtib04_dire675845 foreign key (id_persona) references tib03_persona;
alter table tib04_direccion_persona add constraint FKtib04_dire946989 foreign key (id_tipo) references tib01_tipo_direccion;
alter table tsp02_municipio add constraint FKtsp02_muni551590 foreign key (id_entidad) references tsp01_entidad;
alter table tib02_direccion add constraint FKtib02_dire781797 foreign key (id_entidad, id_municipio) references tsp02_municipio;
alter table tca01_ciclo add constraint FKtca01_cicl996153 foreign key (id_estatus) references tca02_estatus_ciclo;
alter table tca11_ciclo_actividad add constraint FKtca11_cicl6596 foreign key (id_ciclo) references tca01_ciclo;
alter table tad06_informacion_escolar add constraint FKtad06_info671508 foreign key (id_aspirante) references tad02_aspirante;
alter table tad06_informacion_escolar add constraint FKtad06_info134554 foreign key (id_nivel) references tad05_nivel;
alter table tca05_convocatoria add constraint FKtca05_conv404619 foreign key (id_convocatoria) references tca01_ciclo;
alter table tad04_convocatoria_aspirante add constraint FKtad04_conv234823 foreign key (id_aspirante) references tad02_aspirante;
alter table tad04_convocatoria_aspirante add constraint FKtad04_conv861295 foreign key (id_convocatoria) references tca05_convocatoria;
alter table tad04_convocatoria_aspirante add constraint FKtad04_conv980485 foreign key (id_estatus) references tad01_estatus_aspirante;
alter table tad09_pago add constraint FKtad09_pago502777 foreign key (id_convocatoria, id_aspirante) references tad04_convocatoria_aspirante;
alter table tib10_tipo_pago add constraint FKtib10_tipo308796 foreign key (id_categoria) references tib09_categoria_pago;
alter table tca09_convocatoria_criterio add constraint FKtca09_conv867077 foreign key (id_convocatoria) references tca05_convocatoria;
alter table tca08_convocatoria_requisito add constraint FKtca08_conv61333 foreign key (id_convocatoria) references tca05_convocatoria;
alter table tca08_convocatoria_requisito add constraint FKtca08_conv262004 foreign key (id_requisito) references tca04_requisito;
alter table tca09_convocatoria_criterio add constraint FKtca09_conv604461 foreign key (id_criterio) references tca06_criterio;
alter table tad17_entrevistador add constraint FKtad17_entr222150 foreign key (id_entrevistador) references egresado;
alter table tad17_entrevistador add constraint FKtad17_entr67964 foreign key (id_entrevistador) references profesor;
alter table tad16_convocatoria_entrevistador add constraint FKtad16_conv114694 foreign key (id_convocatoria) references tca05_convocatoria;
alter table tad16_convocatoria_entrevistador add constraint FKtad16_conv739424 foreign key (id_entrevistador) references tad17_entrevistador;
alter table tad07_horario add constraint FKtad07_hora726464 foreign key (id_convocatoria, id_entrevistador) references tad16_convocatoria_entrevistador;
alter table egresado add constraint FKegresado505229 foreign key (id_persona) references alumno;
alter table tad13_entrevista add constraint FKtad13_entr534287 foreign key (id_convocatoria, id_aspirante) references tad04_convocatoria_aspirante;
alter table tad13_entrevista add constraint FKtad13_entr829017 foreign key (id_convocatoria, id_entrevistador) references tad16_convocatoria_entrevistador;
alter table tad07_horario add constraint FKtad07_hora371782 foreign key (id_dia) references tib08_dia;
alter table tad12_entrevista_rubro add constraint FKtad12_entr893980 foreign key (id_rubro) references tad10_rubro_entrevista;
alter table tad12_entrevista_rubro add constraint FKtad12_entr893731 foreign key (id_calificacion) references tad11_calificacion_entrevista;
alter table tad14_recomendacion add constraint FKtad14_reco593882 foreign key (id_recomendador) references profesor;
alter table tad13_entrevista add constraint FKtad13_entr787986 foreign key (id_estatus) references tad15_estatus_entrevista;
alter table tad18_direccion add constraint FKtad18_dire755335 foreign key (id_entidad, id_municipio) references tsp02_municipio;
alter table tad19_aspirante_direccion add constraint FKtad19_aspi387711 foreign key (id_direccion) references tad18_direccion;
alter table tad19_aspirante_direccion add constraint FKtad19_aspi892858 foreign key (id_aspirante) references tad02_aspirante;
alter table tca10_periodo add constraint FKtca10_peri919568 foreign key (id_convocatoria, id_criterio) references tca09_convocatoria_criterio;
alter table tau04_acceso add constraint FKtau04_acce672975 foreign key (id_usuario) references tau02_usuario;
alter table tad20_contacto add constraint FKtad20_cont208464 foreign key (id_aspirante) references tad02_aspirante;
alter table tad20_contacto add constraint FKtad20_cont349081 foreign key (id_categoria) references tib05_categoria_contacto;
alter table tad20_contacto add constraint FKtad20_cont787973 foreign key (id_tipo) references tib06_tipo_contacto;
alter table tad21_cita add constraint FKtad21_cita93716 foreign key (id_convocatoria, id_aspirante) references tad04_convocatoria_aspirante;
alter table tad21_cita add constraint FKtad21_cita514569 foreign key (id_convocatoria, id_entrevistador) references tad16_convocatoria_entrevistador;
alter table tad19_aspirante_direccion add constraint FKtad19_aspi154071 foreign key (id_tipo) references tib01_tipo_direccion;
alter table tad09_pago add constraint FKtad09_pago811527 foreign key (id_tipo) references tib10_tipo_pago;
alter table tad14_recomendacion add constraint FKtad14_reco320649 foreign key (id_recomendacion) references tad13_entrevista;
alter table tad12_entrevista_rubro add constraint FKtad12_entr385289 foreign key (id_entrevista) references tad13_entrevista;
alter table tca07_actividad add constraint FKtca07_acti845673 foreign key (id_tipo) references tca03_tipo_actividad;
alter table tca11_ciclo_actividad add constraint FKtca11_cicl621419 foreign key (id_actividad) references tca07_actividad;

